# Generated by Django 2.0.1 on 2018-02-02 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='image',
        ),
    ]
