# Generated by Django 2.0.1 on 2018-02-06 00:01

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180202_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.equip_image_uh),
        ),
    ]
