# Generated by Django 2.0.1 on 2018-02-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_equipment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_bio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
