# Generated by Django 2.0.1 on 2018-02-06 23:21

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180206_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=100)),
                ('classification', models.CharField(max_length=50)),
                ('committed_cast_member', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=50)),
                ('committed_crew_member', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('project_cover_art', models.ImageField(blank=True, null=True, upload_to=accounts.models.project_cover_art_uh)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('project_documents', models.FileField(blank=True, null=True, upload_to=accounts.models.project_document_uh)),
                ('project_images', models.ImageField(blank=True, null=True, upload_to=accounts.models.project_image_uh)),
                ('budget', models.CharField(max_length=50)),
                ('budget_details', models.TextField(max_length=300)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=50)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_bio',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crew',
            name='crew_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_member', to='accounts.Project'),
        ),
        migrations.AddField(
            model_name='cast',
            name='cast_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_member', to='accounts.Project'),
        ),
    ]
