# Generated by Django 2.0.1 on 2018-02-07 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180206_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='cast_member',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='crew_member',
        ),
        migrations.AddField(
            model_name='cast',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cast_members', to='accounts.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crew',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='crew_members', to='accounts.Project'),
            preserve_default=False,
        ),
    ]
