# Generated by Django 2.0.1 on 2018-02-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='character',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cast',
            name='classification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='classification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
