# Generated by Django 2.0.2 on 2018-02-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180208_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tagline',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
