# Generated by Django 2.0.2 on 2018-02-13 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_project_tagline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tagline',
            new_name='tag_line',
        ),
    ]
